# Generated by Django 5.0.4 on 2026-05-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPoruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesija', models.CharField(db_index=True, max_length=100)),
                ('pitanje', models.TextField()),
                ('odgovor', models.TextField()),
                ('jezik', models.CharField(default='hr', max_length=5)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat poruka',
                'verbose_name_plural': 'Chat poruke',
                'ordering': ['-kreirano'],
            },
        ),
    ]
