# Generated by Django 5.0.4 on 2026-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPostavke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacin_prikaza', models.CharField(choices=[('floating', '💬 A — Floating dugme (klasično, donji desni ugao)'), ('uvijek_otvoren', '🪟 B — Uvijek otvoren u uglu (kao Messenger)'), ('sekcija_pocetna', '🎯 C — Velika sekcija na početnoj stranici'), ('kombinacija', '⭐ D — Kombinacija: sekcija na početnoj + dugme svuda'), ('auto_otvori', '🔔 E — Pojavi se sam nakon X sekundi'), ('iskljucen', '🚫 F — Isključen (nigdje se ne prikazuje)')], default='floating', max_length=30, verbose_name='Način prikaza chatbota')),
                ('pozdravna_poruka', models.TextField(default='Pozdrav! 👋 Ja sam vaš AI asistent. Pitajte me bilo što o apartmanima, lokaciji ili izletima u okolici!', help_text='Prva poruka koju gost vidi', verbose_name='Pozdravna poruka')),
                ('naslov', models.CharField(default='AI Asistent', max_length=100, verbose_name='Naslov chatbota')),
                ('podnaslov', models.CharField(default='Online · Odgovara odmah', max_length=200, verbose_name='Podnaslov / status')),
                ('auto_otvori_sekunde', models.IntegerField(default=10, help_text="Samo za način 'Pojavi se sam'", verbose_name='Sekunde prije auto-otvaranja')),
                ('pokazi_sugerirana', models.BooleanField(default=True, help_text='Tagovi sa popularnim pitanjima ispod chata', verbose_name='Pokaži sugerirana pitanja')),
                ('sugerirana_pitanja', models.TextField(default='Koliko košta noćenje?\nGdje se nalazi apartman?\nKoji je najbolji restoran u blizini?\nKako daleko je Plitvička jezera?\nImate li parking?', help_text='Jedno pitanje po liniji (max 6)', verbose_name='Sugerirana pitanja')),
                ('pokazi_na_strankama', models.CharField(choices=[('sve', 'Na svim stranicama'), ('samo_pocetna', 'Samo na početnoj'), ('osim_admin', 'Sve osim admina')], default='sve', max_length=100, verbose_name='Gdje pokazati')),
                ('boja_dugmeta', models.CharField(default='#c9a84c', max_length=20, verbose_name='Boja dugmeta (hex)')),
                ('aktivni_jezici', models.CharField(default='bs,en,de,it', help_text='Razdvoji zarezom: bs,en,de,it', max_length=100, verbose_name='Aktivni jezici')),
            ],
            options={
                'verbose_name': 'Postavke chatbota',
                'verbose_name_plural': 'Postavke chatbota',
            },
        ),
    ]
