# Generated by Django 5.0.4 on 2026-05-08 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200, verbose_name='Naslov')),
                ('sadrzaj', models.TextField(help_text='Možeš koristiti HTML ili AI generator', verbose_name='Sadržaj (HTML ili tekst)')),
                ('poslano', models.BooleanField(default=False, verbose_name='Poslano')),
                ('datum_slanja', models.DateTimeField(blank=True, null=True)),
                ('primatelji', models.IntegerField(default=0, verbose_name='Broj primatelja')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletteri',
                'ordering': ['-kreirano'],
            },
        ),
        migrations.CreateModel(
            name='Pretplatnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ime', models.CharField(blank=True, max_length=100, verbose_name='Ime')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('izvor', models.CharField(default='website', max_length=50, verbose_name='Izvor (website, rezervacija...)')),
                ('pretplaceno', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pretplatnik',
                'verbose_name_plural': 'Pretplatnici newslettera',
                'ordering': ['-pretplaceno'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200, verbose_name='Interni naslov')),
                ('platforma', models.CharField(choices=[('instagram', '📷 Instagram'), ('facebook', '👥 Facebook'), ('tiktok', '🎵 TikTok'), ('twitter', '🐦 X / Twitter'), ('all', '🌍 Sve platforme')], default='all', max_length=20)),
                ('tekst', models.TextField(verbose_name='Tekst posta')),
                ('hashtagovi', models.TextField(blank=True, verbose_name='Hashtagovi')),
                ('slika', models.ImageField(blank=True, null=True, upload_to='social/')),
                ('datum_objave', models.DateTimeField(blank=True, null=True, verbose_name='Datum objave')),
                ('status', models.CharField(choices=[('nacrt', '📝 Nacrt'), ('zakazano', '⏰ Zakazano'), ('objavljeno', '✅ Objavljeno')], default='nacrt', max_length=20)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post za društvene mreže',
                'verbose_name_plural': 'Postovi za društvene mreže',
                'ordering': ['-kreirano'],
            },
        ),
        migrations.CreateModel(
            name='StatistikaPosjete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('broj_posjeta', models.IntegerField(default=0)),
                ('broj_jedinstvenih', models.IntegerField(default=0)),
                ('najposjecenija_stranica', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistike posjeta',
                'ordering': ['-datum'],
            },
        ),
    ]
