# Generated by Django 5.0.4 on 2026-05-01 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ime', models.CharField(max_length=100, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=100, verbose_name='Prezime')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('drzava', models.CharField(blank=True, max_length=50, verbose_name='Država')),
                ('datum_dolaska', models.DateField(verbose_name='Datum dolaska')),
                ('datum_odlaska', models.DateField(verbose_name='Datum odlaska')),
                ('broj_gostiju', models.IntegerField(default=1, verbose_name='Broj gostiju')),
                ('cijena_po_noci', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ukupno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('cekanje', '⏳ Čeka potvrdu'), ('potvrdjeno', '✅ Potvrđeno'), ('placeno', '💳 Plaćeno'), ('otkazano', '❌ Otkazano'), ('zavrseno', '🏁 Završeno')], default='cekanje', max_length=20)),
                ('izvor', models.CharField(choices=[('direktno', 'Direktna rezervacija'), ('booking', 'Booking.com'), ('airbnb', 'Airbnb'), ('ostalo', 'Ostalo')], default='direktno', max_length=20)),
                ('napomene_gosta', models.TextField(blank=True, verbose_name='Napomene gosta')),
                ('napomene_vlasnika', models.TextField(blank=True, verbose_name='Privatne napomene')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to='apartman.apartman')),
                ('gost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rezervacije', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezervacija',
                'verbose_name_plural': 'Rezervacije',
                'ordering': ['-datum_dolaska'],
            },
        ),
        migrations.CreateModel(
            name='ZauzetTermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
                ('izvor', models.CharField(default='booking', max_length=20)),
                ('napomena', models.CharField(blank=True, max_length=200)),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zauzeti_termini', to='apartman.apartman')),
            ],
            options={
                'verbose_name': 'Zauzet termin',
                'verbose_name_plural': 'Zauzeti termini',
            },
        ),
    ]
