# Generated by Django 5.0.4 on 2026-05-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacije', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='jezik',
            field=models.CharField(choices=[('hr', 'Hrvatski'), ('en', 'English'), ('de', 'Deutsch'), ('it', 'Italiano')], default='hr', max_length=5, verbose_name='Jezik gosta'),
        ),
    ]
