# Generated by Django 5.0.4 on 2026-05-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, verbose_name='Naziv')),
                ('podnaslov', models.CharField(blank=True, max_length=300, verbose_name='Podnaslov')),
                ('opis', models.TextField(verbose_name='Opis')),
                ('kapacitet', models.IntegerField(verbose_name='Broj gostiju')),
                ('spavace_sobe', models.IntegerField(default=1, verbose_name='Spavaće sobe')),
                ('kupaonice', models.IntegerField(default=1, verbose_name='Kupaonice')),
                ('cijena_po_noci', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cijena po noći (€)')),
                ('minimalni_boravak', models.IntegerField(default=2, verbose_name='Min. noći')),
                ('adresa', models.CharField(max_length=300, verbose_name='Adresa')),
                ('grad', models.CharField(max_length=100, verbose_name='Grad')),
                ('lat', models.FloatField(verbose_name='Geografska širina')),
                ('lng', models.FloatField(verbose_name='Geografska dužina')),
                ('wifi_lozinka', models.CharField(blank=True, max_length=100, verbose_name='WiFi lozinka')),
                ('pravila_kuce', models.TextField(blank=True, verbose_name='Pravila kuće')),
                ('check_in', models.TimeField(default='15:00', verbose_name='Check-in od')),
                ('check_out', models.TimeField(default='11:00', verbose_name='Check-out do')),
                ('aktivan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Apartman',
                'verbose_name_plural': 'Apartmani',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, verbose_name='Naziv')),
                ('ikona', models.CharField(choices=[('wifi', '📶 WiFi'), ('parking', '🅿️ Parking'), ('klima', '❄️ Klima'), ('bazen', '🏊 Bazen'), ('tv', '📺 TV'), ('kuhinja', '🍳 Kuhinja'), ('masina_rublje', '👕 Mašina za rublje'), ('terasa', '🌿 Terasa'), ('roštilj', '🔥 Roštilj'), ('kucni_ljubimci', '🐾 Kućni ljubimci OK'), ('more', '🌊 Pogled na more'), ('planine', '⛰️ Pogled na planine')], max_length=20, verbose_name='Ikona')),
                ('apartman', models.ManyToManyField(related_name='amenities', to='apartman.apartman')),
            ],
            options={
                'verbose_name': 'Sadržaj',
                'verbose_name_plural': 'Sadržaji',
            },
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_gosta', models.CharField(max_length=100, verbose_name='Ime gosta')),
                ('drzava', models.CharField(blank=True, max_length=50, verbose_name='Država')),
                ('ocjena', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Ocjena (1-5)')),
                ('komentar', models.TextField(verbose_name='Komentar')),
                ('datum', models.DateField(verbose_name='Datum posjeta')),
                ('odobreno', models.BooleanField(default=False, verbose_name='Odobreno za prikaz')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzije', to='apartman.apartman', verbose_name='Apartman')),
            ],
            options={
                'verbose_name': 'Recenzija',
                'verbose_name_plural': 'Recenzije',
                'ordering': ['-kreirano'],
            },
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='slike/', verbose_name='Slika')),
                ('naslov', models.CharField(blank=True, max_length=100, verbose_name='Opis slike')),
                ('naslovna', models.BooleanField(default=False, verbose_name='Naslovna slika')),
                ('redoslijed', models.IntegerField(default=0, verbose_name='Redoslijed')),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike', to='apartman.apartman', verbose_name='Apartman')),
            ],
            options={
                'verbose_name': 'Slika',
                'verbose_name_plural': 'Slike',
                'ordering': ['redoslijed'],
            },
        ),
    ]
