# Generated by Django 5.0.4 on 2026-05-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('ikona', models.CharField(default='📍', max_length=10)),
                ('boja', models.CharField(default='#3b82f6', max_length=7)),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, verbose_name='Naziv')),
                ('opis', models.TextField(verbose_name='Opis')),
                ('kratki_opis', models.CharField(max_length=200, verbose_name='Kratki opis')),
                ('udaljenost_km', models.FloatField(verbose_name='Udaljenost (km)')),
                ('trajanje_min', models.IntegerField(blank=True, null=True, verbose_name='Trajanje vožnje (min)')),
                ('adresa', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField(verbose_name='Geografska širina')),
                ('lng', models.FloatField(verbose_name='Geografska dužina')),
                ('slika', models.ImageField(blank=True, upload_to='izleti/', verbose_name='Slika')),
                ('web_link', models.URLField(blank=True, verbose_name='Web stranica')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='Google Maps link')),
                ('cijena', models.CharField(blank=True, max_length=50, verbose_name="Cijena (npr. 'Besplatno' ili '10€')")),
                ('radno_vrijeme', models.CharField(blank=True, max_length=200, verbose_name='Radno vrijeme')),
                ('preporuceno', models.BooleanField(default=False, verbose_name='Naš prijedlog ⭐')),
                ('redoslijed', models.IntegerField(default=0)),
                ('aktivno', models.BooleanField(default=True)),
                ('kategorija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lokacije', to='izleti.kategorija')),
            ],
            options={
                'verbose_name': 'Lokacija',
                'verbose_name_plural': 'Lokacije',
                'ordering': ['redoslijed', 'udaljenost_km'],
            },
        ),
    ]
